#ifndef _RUNTIME_LOADER_ARCH_M68K_ARCH_RUNTIME_LOADER_H_
#define _RUNTIME_LOADER_ARCH_M68K_ARCH_RUNTIME_LOADER_H_

#include <sys/types.h>

#endif /* _RUNTIME_LOADER_ARCH_M68K_ARCH_RUNTIME_LOADER_H_ */
